package adapters.dam;

import adapters.DBGateway;
import adapters.TokenSigner;
import businessrules.dai.VendorRepository;
import entities.Shop;
import entities.Vendor;
import framework.JWTSigner;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

/**
 * The data access manager for Vendor database.
 */
public class VendorDB implements VendorRepository {
    /**
     * The Database connector.
     */
    DBGateway databaseConnector;
    /**
     * The Table name.
     */
    final String tableName = "Vendor";
    /**
     * The Token signer.
     */
    TokenSigner tokenSigner;


    /**
     * Instantiates a new Vendor db.
     *
     * @param databaseConnector the database connector
     */
    public VendorDB(DBGateway databaseConnector) {
        this.databaseConnector = databaseConnector;
        this.tokenSigner = new JWTSigner();
    }

    /**
     * @param id the id of the entry to get from the database
     * @return the constructed object of the given id from the database
     */
    @Override
    public Vendor read(String id) {
        return loadVendorFromJSON(databaseConnector.read(tableName, id));
    }

    /**
     * Method for updating a vendor entry in the database
     * @param id the id of the vendor entry
     * @param item the updated vendor information
     * @return whether the update was successful or not
     */
    @Override
    public boolean update(String id, Vendor item) {
        return databaseConnector.update(tableName, id, loadJSONFromVendor(item));
    }
    /**
     * @param item the entity to add to the database, the ID will initially be null
     * @return The new ID of the object just created, generated by the database
     */
    @Override
    public String create(Vendor item) {
        return databaseConnector.create(tableName, loadJSONFromVendor(item));
    }

    /**
     * Method for retrieving multiple vendors from the database
     * @param parameter the parameter to search by
     * @param needle the value of the parameter to find
     * @return a list of vendor entities that match the requirements
     */
    @Override
    public List<Vendor> readMultiple(String parameter, String needle) {
        List<Vendor> vendorList = new ArrayList<>();
        List<JSONObject> rawVendors = databaseConnector.readMultiple(tableName, parameter, needle);
        for(JSONObject rawVendor: rawVendors){
            vendorList.add(loadVendorFromJSON(rawVendor));
        }
        return vendorList;
    }

    /**
     * Method for retrieving a vendor from the database
     * @param fieldName the field to search by
     * @param needle the value of the field to find
     * @return a vendor entity that matches the requirements
     */
    @Override
    public Vendor findOneByFieldName(String fieldName, String needle) {
        if(databaseConnector.readOne(tableName, fieldName, needle) != null) {
            return loadVendorFromJSON(databaseConnector.readOne(tableName, fieldName, needle));
        }
        return  null;

    }

    /**
     * @param userToken the user token corresponding to the user it is attached to
     * @return a vendor entity corresponding to that token
     */
    @Override
    public Vendor getUserFromToken(String userToken) {
        String info = tokenSigner.getIdFromToken(userToken);
        String userId = info.split(",")[0];
        if(userId.contains("ERROR")){
            return null;
        }
        return read(userId);
    }

    /**
     * @param username the customer's username
     * @param password the customer's password
     * @return Token associated with that user session
     */
    @Override
    public String authenticateUser(String username, String password) {
        Vendor vendor = findOneByFieldName("username", username);
        if(vendor == null){
            return null;
        }
        if(!vendor.getHashedPassword().equals(password)){
            return null;
        }
        String token_parameter = vendor.getId() + "," +vendor.getUserName() +","+vendor.getShop().getId();
        return tokenSigner.generateToken(token_parameter);
    }

    /**
     * Method for converting a JSON object to a vendor entity
     *
     * @param jsonObject the JSON data
     * @return the corresponding vendor entity
     */
    public Vendor loadVendorFromJSON(JSONObject jsonObject) {
        ShopDB shopLoader = new ShopDB(databaseConnector);
        try{
            String id = jsonObject.getString("id");
            String username = jsonObject.getString("username");
            String hashedPassword = jsonObject.getString("password");
            String shopId = jsonObject.getString("shopId");
            Shop shop = shopLoader.read(shopId);
            return new Vendor(id, username, hashedPassword, shop);
        }catch (JSONException e){
            return null;
        }
    }

    /**
     * Method for converting a vendor entity to a JSON object
     *
     * @param vendor the shop entity
     * @return the corresponding JSON object
     */
    public static JSONObject loadJSONFromVendor(Vendor vendor){
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("id", vendor.getId());
        jsonObject.put("username", vendor.getUserName());
        jsonObject.put("password", vendor.getHashedPassword());
        jsonObject.put("shopId", vendor.getShop().getId());
        return jsonObject;
    }


}
